### ISSUE TITLE
Failed to get diff of files for lint

### ISSUE THREAD

**Issue by GaboFDC** [github/super-linter#1258]
## Describe the bug

There is an error when checking the changed files:
`File:{fatal: master...dad356fc1a8f8fe0ed036fb518762fd1f32a9c2b: no merge base} existed in commit data, but not found on file system, skipping...`

This means there are 2 bugs. 
The command is failing fatally, but the script continues to work as if it didn't fail.
And also, the command is broken in some way and not finding the merge base.

## Expected behavior

The linter should continue to work as expected. We have yet another broken release :/

## Steps to Reproduce

I think the problem is related to squash commits. But also the way it is being used, makes that if the command fails, it is not properly handled.

**Comment by GaboFDC** [comment]
Here is an example of the error https://github.com/GaboFDC/test-super-linter/pull/2
But there I have not squash and merged any commit.
Which leads me to think that the error is more generalized.

**Comment by bcspragu** [comment]
I just ran into this (on a private org repo) on a PR where the only difference compared to hundreds of other PRs I've done in the past was that I created the PR with `gh pr create` instead of the button that appears in the UI. Could be unrelated to that (and instead related to a new release of super-linter), but figured it was worth mentioning. Also worth mentioning is that it doesn't appear to be a flake, it's appeared on three successive runs.
