### ISSUE TITLE
Stop making mistakes in the release process, automate it

### ISSUE THREAD

**Issue by alerque** [github/super-linter#1390]
As can be seen from the likes of the last 3 releases (see e.g. 9cd2793) the current process involving manually bumping values in strings as part of the release process is silly and error prone. It can easily be automated.

There would be lots of ways to to it, but for a case study with [CaSILE](https://github.com/sile-typesetter/casile) I'm using [`standard-version`](https://github.com/conventional-changelog/standard-version) which is in pretty wide use, but there are other similar tools in various languages. The business end is [this bump script](https://github.com/sile-typesetter/casile/blob/master/build-aux/action-updater.js) which gets called from the [`package.json` under `standard-version.bumpFiles`](https://github.com/sile-typesetter/casile/blob/29fc67bf3b830483c669493a5244de2a50784216/package.json#L55). In this case the entire release process is automated including changelog generation and posting releases from CI, but you could easily get away with rolling your own script just to bump and tag the right bits.

**Comment by admiralAwkbar** [comment]
Hello @alerque 
We do have an automated process for the release process but are still working out the kinks in it...

As you can see:
- We need to update the `action.yml` in the release process to make sure the release, and the version are in sync. If not, then users will get a version different than what they have asked for. This is due to the nature of this being a Docker container and not static in the codebase.

This process is frustrating... As it's prone to natural errors like sites being down, npm taking too long, etc...
That seemed to be the release failure yesterday.

I do agree, it needs to be better and I'm trying to find some additional cycle to help make the automation around this process less error-prone and more resilient.

I appreciate the help and am sorry if this has caused any issues for you. 
We always welcome pull requests to help make this tool better for all

thanks!
