### ISSUE TITLE
Add Commitlint

### ISSUE THREAD

**Issue by Kurt-von-Laven** [github/super-linter#1668]
**Is your feature request related to a problem? Please describe.**
Commit messages often don't get the attention they deserve. Many projects have adopted standardized commit message formats, but enforcing them can be tedious for both the author and reviewer. It seems fitting for a GitHub super linter to include a tool for linting git commit messages.

**Describe the solution you'd like**
Include [commitlint](https://commitlint.js.org/) as a supported linter.

**Describe alternatives you've considered**
I have considered recommending [git-commit-msg-linter](https://yarnpkg.com/package/git-commit-msg-linter) instead, which is less configurable but does offer [some decent points in its own defense](https://yarnpkg.com/package/git-commit-msg-linter#1-why-not-conventional-changelogcommitlint). I have also considered configuring commitlint locally for our project.

**Additional context**
Here are the [local](https://commitlint.js.org/#/guides-local-setup) and [CI](https://commitlint.js.org/#/guides-ci-setup) setup guides.

**Comment by admiralAwkbar** [comment]
@Kurt-von-Laven 
This is an interesting idea.

My main issue with this is that if a user pushes a commit with a bad *string*, then pushes more commits, they will eventually have to go back, and amend the commit before, thus updating the history.

This could be very problematic to many users on how to achieve this and fix this.

I see this tool as a great tool for `pre-commit hooks` that help make sure no bad commit messages make it from your local environment to the source of truth, but I think this could be problematic...

@ferrarimarco @GaboFDC @nemchik your thoughts would be greatly appreciated

**Comment by Kurt-von-Laven** [comment]
That's an interesting point. I feel like a team that didn't know how to run `git rebase -i main` and select the reword option would hopefully have the sense to either Google that, configure the pre-commit hook as well, or disable commitlint in CI. I could be overestimating folks since I had the luxury of being taught git by Linux kernel developers. I get how it would be problematic if the tool were creating too much friction for people though, since then it would likely end up disabled.

**Comment by nemchik** [comment]
I am inclined to agree that linting commit messages can become a barrier for new collaborators.

Many projects will see new collaborators make use of the web editor to make commits, and may not see hints such as contributing guidelines until they make it to actually opening a PR (which is after having made a commit). Editing existing commit messages ends up needing to be done locally, so collaborators unfamiliar with cloning (who have just made a change via the web editor) would be presented with a steeper learning curve than they may have anticipated when trying to contribute a simple change.

Another quick example would be a new collaborator clones the repo, begins making changes and commits, does multiple commits, and then pushes to their fork in order to make a PR. In that scenario, would commitlint only be run against the most recent commit in the branch (since actions/CI would only run against the most recent commit)?

I do love the idea of giving commit messages more attention, but i feel like this is a decision for project owners to maintain in their branches, and when accepting PRs they may choose to squash and reword commits in order to maintain their commit message history.

pre-commit is a better objective than linting after commits are pushed to a remote (where super-linter would be most likely to interact with the commits).

**Comment by Kurt-von-Laven** [comment]
> Many projects will see new collaborators make use of the web editor to make commits, and may not see hints such as contributing guidelines until they make it to actually opening a PR (which is after having made a commit). Editing existing commit messages ends up needing to be done locally, so collaborators unfamiliar with cloning (who have just made a change via the web editor) would be presented with a steeper learning curve than they may have anticipated when trying to contribute a simple change.

That is a great point that I hadn't considered. The only thing I could think of to address this would be to disable commitlint by default, but offer a flag to enable it. That feels counter-intuitive though given that all of the other linters are enabled by default.

> Another quick example would be a new collaborator clones the repo, begins making changes and commits, does multiple commits, and then pushes to their fork in order to make a PR. In that scenario, would commitlint only be run against the most recent commit in the branch (since actions/CI would only run against the most recent commit)?

The point is likely moot, but I was imagining that commitlint would run against all of the commits in the pull request. I think this is [relatively straightforward](https://github.community/t/how-to-get-the-full-range-of-commits-for-a-pr/17527), but haven't tried it yet myself.

> I do love the idea of giving commit messages more attention, but i feel like this is a decision for project owners to maintain in their branches, and when accepting PRs they may choose to squash and reword commits in order to maintain their commit message history.

Ah, yes, I could certainly see that having frequently reworded others' commits myself.

> pre-commit is a better objective than linting after commits are pushed to a remote (where super-linter would be most likely to interact with the commits).

Yes, the commitlint authors make this point in their documentation as well that it is most helpful when configured locally. I suppose even then the tool has the same drawback of not being run in the web editor.

**Comment by Kurt-von-Laven** [comment]
Upon further reflection and taking the points that have been raised into consideration, I feel that the best solution would be a completely separate commitlint action, which is obviously out of scope for issues on this repository. Please feel free to close this issue unless you wish to offer commitlint behind a flag.
