### ISSUE TITLE
Supporting Custom flake8 Plugins

### ISSUE THREAD

**Issue by urosisakovic** [github/super-linter#1735]
Does GitHub Super Linter support custom flake8 plugins? If so, can you please point me where to look for instructions on enabling them. Thank you.

**Comment by admiralAwkbar** [comment]
@urosisakovic That's a great question, currently I don't think it's supported, and the reason is we would have to install the plugin inside the **Super-Linter** container before run time... And it does not appear we can load them at run time...

So it seems the best option is to have a step before the super-linter runs, and install the custom plugins, then when the **Super- Linter** runs it should be able to pull them in?

**Comment by admiralAwkbar** [comment]
Also sorry for the wait on this response, was on a slight vacation and wasn't feeling like working :)
