### ISSUE TITLE
Lint for CSHARP

### ISSUE THREAD

**Issue by chukkalasandeep** [github/super-linter#1736]
Hi,

For the CSHARP lint it is not fixing the spaces, styles, analyzers, In the github flow it is showing errors and exiting with errors. I checked the "linter.sh" for the CSHARP command and it is using "--check" flag along with the dotnet format command, can reason why it is being added because of that the fixes are not done and erroring out.

**Comment by admiralAwkbar** [comment]
Hey, @chukkalasandeep  For the **Super-Linter** We only do linting, and not any fixes back to the codebase. If we did that, we would also need to commit those changes back to your codebase. Since we try to follow the `read only` and not `write` style, this is why we use `--check`.

We then report any issues we find, and error accordingly. I hope this sheds some light on the issue

**Comment by chukkalasandeep** [comment]
Hi @admiralAwkbar , 

Thanks for the explanation, but for the errors does it show as summary?

**Comment by admiralAwkbar** [comment]
@chukkalasandeep 
Hey when the  **Super-Linter** runs, it will show those lines and report that they need to be fixed and mark the job as a failure.

Hope this helps!
