### ISSUE TITLE
Separate black and snakefmt depedencies

### ISSUE THREAD

**Issue by jalaziz** [github/super-linter#1828]
**Is your feature request related to a problem? Please describe.**

Currently, `black` is pinned to a fairly _old_ version due to `snakefmt`. This effectively prevents `super-linter` from upgrading `black` as it can cause conflicts and break `snakefmt`. While `snakefmt` is actively maintained, it may choose not to upgrade `black` for any number of reasons.

**Describe the solution you'd like**

It would be great if the version of `black` used by `super-linter` was not dependent on `snakefmt` dependency requirements for users that don't use `snakefmt`. Even better would be the version of `black` being made configurable to match the requirements of the project using the linter.

**Describe alternatives you've considered**

I have opened up a PR at snakemake/snakefmt#116, but that does not seem like a long-term solution. The other alternative seems to be to not use `super-linter` and use `black` directly.

**Additional context**

This issue was brought up before when upgrading to `black` 20.0 in #1212, #807, #840, and #762. Would be good to solve this for good.

`black` officially releases self-contained binaries now, which could help. However, this may mean manually updating `black` instead of relying on dependabot.

**Comment by admiralAwkbar** [comment]
@jalaziz 
Hey yeah, this has been a fun one...

Pip seems to be the most fun to keep on track and has been fun trying to stop the dependency madness...

I would love if we could install black as a binary and move away from the current way.. that would help solve a lot of my current issues...

I tried a quick search on where and how I can install the black binary instead of the pip install.. Can you link me and ill try to get this baked in

**Comment by jalaziz** [comment]
@admiralAwkbar Currently, it seems the only place to download the binaries are from the [black's releases page](https://github.com/psf/black/releases).
