### ISSUE TITLE
Ruby: Switch from RuboCop to StandardRB

### ISSUE THREAD

**Issue by gobijan** [github/super-linter#188]
The beauty of Ruby Standard Style is that it's simple. No one wants to maintain multiple hundred-line style configuration files for every module/project they work on. RuboCops defaults are not that complete.

Under the hood standard uses RuboCop but with saner community defaults that are not customized by GitHub only.
In my opinion using standard better match the philosophy of this project.

https://github.com/testdouble/standard

**Comment by zkoppert** [comment]
I'm checking with other GitHub folks but I would like to hear more opinions from others to try to understand if there is consensus around this.

**Comment by jhawthorn** [comment]
It looks like this is currently using `rubocop-github`, which has some good rules, but I wouldn't recommend for use outside GitHub. I think either the default rules or standard are good choices.

I'm not too familiar with how this action works, but we might be able to get the best of both worlds by:
* If a .rubocop.yml exists in the project, use that
* Otherwise run standard with its rules

**Comment by zkoppert** [comment]
Thanks @jhawthorn! That sounds reasonable to me. Any objections @gobijan?

**Comment by gobijan** [comment]
I really like the proposal :) Thx for the openness.
Do you need any support in implementation?

**Comment by zkoppert** [comment]
@gobijan Yes please. Feel free to open a PR. I will mark this as ready.

**Comment by artob** [comment]
I'm late to the party, but I feel I must point out that you might be overestimating StandardRB's fan base a little. Just because something names itself as "the standard" doesn't mean that it is. Most existing Ruby projects would _not_ pass StandardRB's rather opinionated ruleset.

Switching from the current ruleset to StandardRB would be a breaking change for current users of the Super-Linter.

**Comment by admiralAwkbar** [comment]
I think we can make this an add the StandardRB as an additional check

**Comment by zkoppert** [comment]
smart idea @admiralAwkbar!

**Comment by krtschmr** [comment]
Now that standard.rb is officiall in version 1, this should be reconsidered. 
https://blog.testdouble.com/posts/2021-03-04-announcing-standard-ruby-1.0/
