### ISSUE TITLE
Add sqlfluff linter configuration support

### ISSUE THREAD

**Issue by siarhei-prystauka** [github/super-linter#1990]
**Is your feature request related to a problem? Please describe.**
I'm not able to configure sqlfluff linter for T-SQL dialect

**Describe the solution you'd like**
Add sqlfluff linter configuration support via configuration file in linters folder

**Comment by tunetheweb** [comment]
Hi, I'm one of the SQLFluff maintainers (who also is a big user and fan of the GitHub Super Linter project hence why I noticed this issue!)

First up, to set expectations, SQLFluff has **_only just_** implemented T-SQL support in 0.6.5 and it's pretty basic at the moment to be perfectly honest. But we have people actively working and contributing towards it so hoping to see it improve in future. But basic queries should work. Given that you may want to consider keeping an eye on the [SQLFluff Issues](https://github.com/sqlfluff/sqlfluff/issues) and [Releases](https://github.com/sqlfluff/sqlfluff/releases). Due to release cycles the GitHub Super Linter is often a version or two behind (we're on 0.6.6 for example but this project still has 0.6.5 for now), which might be more relevant given the early support of T-SQL. But the team here do keep it up to date weekly so shouldn't be too far behind, but just making you aware.

Anyway on to your main question. Currently SQLFluff does not allow specifying config via an explicit file path location (e.g. `.github/linters/.sqlfluff`). So, until that is resolved, this is an issue for SQLFluff and not the Super-Linter. It's being tracked here: https://github.com/sqlfluff/sqlfluff/issues/1244

Saying that, it's not a big issue, because you CAN configure SQLFluff when using it with the Super Linter - just not by using the `.github/linters/` folder like the other linters. This is because SQLFluff does pick up a `.sqlfluff` config file from the location of the SQL file (or any of its parents folders). So I'm using the GitHub Super-Linter with SQLFluff with a `.sqlfluff` config file in my `/sql` folder in my git repo and therefore the SQLFLuff linter in the GitHub Super Linter uses that for any `.sql` file in that directory or any sub-directory. I can then further refine it if I want, with another, more specific `.sqlfluff` config file in a subdirectory if I want different config for those files.

Let me know if that's enough to answer your question and close this issue. Or happy to answer further questions here, on the SQLFluff repo, or on the SQLFluff slack.

**Comment by siarhei-prystauka** [comment]
Hi,
Got it.
Thank you very much for detailed clarification.

**Comment by admiralAwkbar** [comment]
@tunetheweb Thanks for the help on this! Let me know what I can do to help keep this up to date and get that config support

Also will be cutting a new release later today I think to catch up :)

**Comment by jpy-git** [comment]
FYI we added the ability to specify custom config paths for SQLFluff in both the CLI and the API in the recent 0.9.0 [release](https://github.com/sqlfluff/sqlfluff/releases/tag/0.9.0). It's the `--config` argument for the CLI and the `config` argument for the API.

**Comment by tunetheweb** [comment]
Hey @jpy-git there's an open issue in #2184 to track this. Just waiting on dependabot updating super-linter and then I'll open a PR for that.

**Comment by jpy-git** [comment]
@tunetheweb perfect, I remembered seeing this issue a while back. Thanks for handling this 👍

**Comment by tunetheweb** [comment]
FYI opened #2361 to allow config file to be placed in usual location (`.github/linters`).
