### ISSUE TITLE
Error on local: /action/lib/functions/log.sh: line 47: date: command not found

### ISSUE THREAD

**Issue by A2DNEW** [github/super-linter#2066]
I want to use super-linter on local.
I installed super-linter with docker and I run this commend:
`docker run -e RUN_LOCAL=true -v /Users/MH/Library/Mobile\ Documents/com\~apple\~CloudDocs/Project/MyCode:/tmp/lint github/super-linter`
And I get this log:
```
2021-10-23 21:24:57 [INFO]   Successfully gathered list of files...
2021-10-23 21:24:57 [INFO]   Found PHP files to validate, and [VALIDATE_PHP_PSALM] set to true, need to run composer install
2021-10-23 21:24:57 [INFO]   looking for composer.json in the users repository...
/action/lib/functions/log.sh: line 47: date: command not found
/action/lib/functions/log.sh: line 39: tee: command not found
/action/lib/functions/log.sh: line 50: date: command not found
/action/lib/functions/log.sh: line 39: tee: command not found
/action/lib/functions/log.sh: line 52: date: command not found
/action/lib/functions/log.sh: line 39: tee: command not found
/action/lib/linter.sh: line 765: sh: command not found
```

**Comment by elfarsaouiomar** [comment]
some issue here;

**Comment by elfarsaouiomar** [comment]
> I want to use super-linter on local. I installed super-linter with docker and I run this commend: `docker run -e RUN_LOCAL=true -v /Users/MH/Library/Mobile\ Documents/com\~apple\~CloudDocs/Project/MyCode:/tmp/lint github/super-linter` And I get this log:
> 
> ```
> 2021-10-23 21:24:57 [INFO]   Successfully gathered list of files...
> 2021-10-23 21:24:57 [INFO]   Found PHP files to validate, and [VALIDATE_PHP_PSALM] set to true, need to run composer install
> 2021-10-23 21:24:57 [INFO]   looking for composer.json in the users repository...
> /action/lib/functions/log.sh: line 47: date: command not found
> /action/lib/functions/log.sh: line 39: tee: command not found
> /action/lib/functions/log.sh: line 50: date: command not found
> /action/lib/functions/log.sh: line 39: tee: command not found
> /action/lib/functions/log.sh: line 52: date: command not found
> /action/lib/functions/log.sh: line 39: tee: command not found
> /action/lib/linter.sh: line 765: sh: command not found
> ```

#### this work for me

```yaml
  - name: Lint Code Base
    uses: github/super-linter@v4
    env:
      VALIDATE_ALL_CODEBASE: true
      VALIDATE_PHP_PSALM: false
      DEFAULT_BRANCH: master
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ErichWilliStein** [comment]
Erich

A2DNEW ***@***.***> schrieb am Sa., 23. Okt. 2021, 23:34:

**Comment by zkoppert** [comment]
I was unable to recreate this issue by doing the following:
- Login to docker ghcr.io with a read packages authenticated Token
- Get the latest docker image `docker pull ghcr.io/github/super-linter:latest`
- ☝🏻 That took forever... 😓 
- Clone some PHP code `git clone --depth 1 https://github.com/danielmiessler/SecLists.git`
- Run Docker image on the code`docker run -e RUN_LOCAL=true -v /Users/zackkoppert/repos/SecLists:/tmp/lint github/super-linter`
- no similar error resulted

Since it doesn't seem widespread and there is a workaround (turn off php psalm), I'll close this ticket. Re-open if it becomes a more widespread issue or the workaround is no longer effective.
