### ISSUE TITLE
Why is gitleaks configured to report error on "LinkedIn Client ID"?

### ISSUE THREAD

**Issue by gmacario** [github/super-linter#2129]
The subject says it all.

I have a Markdown file which contains links to people profiles on LinkedIn, and since recently Super-Linter reports errors.

I guess this is due to https://github.com/github/super-linter/blame/main/TEMPLATES/.gitleaks.toml#L56-L59

Is there a reason why links to LinkedIn profiles are considered harmful?

**Comment by gmacario** [comment]
I just realized that the rule is also present upstream

https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L56-L59

I will ask the same question on https://github.com/zricethezav/gitleaks

**Comment by admiralAwkbar** [comment]
@gmacario Thanks for catching this.
If there is anything I need to push would be glad to help!

**Comment by zkoppert** [comment]
I checked the linked upstream issue. Looks like we are ok to close this one.

**Comment by inerte** [comment]
@zkoppert 

I came across this issue because my LinkedIn profile url is being reported as a leak:

https://linkedin.com/in/julionobrega

If it's slightly different, then it's not a leak:

https://linkedin.com/in/julionobreg

The ["LinkedIn Client ID" rule regex at gitleaks](https://github.com/zricethezav/gitleaks/blob/9358e845883077591b8d4107c452d7aa70cd60ab/config/gitleaks.toml#L426) is different than the one [present at super-leaks](https://github.com/github/super-linter/blob/c3ad7bace60b7845bb563a858c0198f7b738724f/TEMPLATES/.gitleaks.toml#L58)
