### ISSUE TITLE
Add android support for ktlint

### ISSUE THREAD

**Issue by alexandrefavre4** [github/super-linter#2666]
Please add Android support for ktlint 🙏 

ktlint command accepts a `--android` parameter to use Kotlin codestyles more suitable for Android.

We could achieve that by adding the following changes to `/lib/linter.sh`:
```bash
KOTLIN_ANDROID="${KOTLIN_ANDROID:-false}"

if [ "${KOTLIN_ANDROID}" == 'false' ]; then
  LINTER_COMMANDS_ARRAY['KOTLIN']="ktlint"
else
  LINTER_COMMANDS_ARRAY['KOTLIN']="ktlint --android"
fi
```

Then, we will be able to specify which linter command to use in our `linter.yml`:
```yaml
VALIDATE_KOTLIN: true
KOTLIN_ANDROID: true
```

**Comment by ferrarimarco** [comment]
Hi @alexandrefavre4.

This is a relatively low hanging fruit because ktlint is already installed in the image.

Anyway, I'd rather introduce another language variant (which can be named as well `KOTLIN_ANDROID`) rather than using and environment variable to conditionally change the command. I'd also consider if there are ways we can detect when a Kotlin file has to be linted with `ktlint` or `ktlint --android`.

Feel free to open a PR for this!

**Comment by alexandrefavre4** [comment]
Hey @ferrarimarco, thank you for your answer. I created a draft pr (#2670) with the changes you suggested (new language variant instead of an environment variable). Let me know what is missing to set this pr as ready for review.

**Comment by ferrarimarco** [comment]
Thanks @alexandrefavre4 ! I've commented in that PR directly :)
