### ISSUE TITLE
Linting .tsx and .jsx files

### ISSUE THREAD

**Issue by bjarkehs** [github/super-linter#352]
Hey!

Is there something I'm missing in order for it to lint my .tsx files? (Typescript JSX files)

It seems only my .ts files are linted with eslint.

**Comment by StalkAltan** [comment]
Hey @bjarkehs !

It looks like the reason super-linter isn't linting .jsx/.tsx files is because the JS/TS linter configurations are only searching for .js/.ts

See here for an example from the code: [link](https://github.com/github/super-linter/blob/6c152d271e400f0db27514e0d1a647b41937741b/lib/linter.sh#L1032)

**Comment by admiralAwkbar** [comment]
@bjarkehs should they be linted the exact same way? if that is the case, it should be easy enough for us to make a PR that also searches for those extensions :)

Sorry my JS/TS is not the strongest...
