### ISSUE TITLE
Pre-releases

### ISSUE THREAD

**Issue by nemchik** [github/super-linter#358]
**Is your feature request related to a problem? Please describe.**
Right now there is no way aside from testing the test cases in this repo to see how the linter would run on various types of code, specifically in a scenario where there is a new linter being added to the project. Test cases should be added alongside new linters before release, but pre-releases will also allow additional end user testing and reporting.

**Describe the solution you'd like**
Pre-releases in this repo and tags on docker that are specifically indicated as pre-release tags and never tied to the `:latest` tag should provide users the ability to test things being considered prior to a standard release. Of course pre-releases should come with the disclaimer that things may change or be removed prior to the next full release. Ex: adding a new linter would hit a pre-release first, and if all is well it makes the next full release, but if not then it might be sidelined or removed from consideration to be added.

This probably also means maintaining a dev branch here in this repo and probably requesting all PRs be made against the dev branch except PRs from the dev branch to the master branch when it's time to bring code over for a full release.

**Describe alternatives you've considered**
In the above description I mentioned pre-release tags on the docker image. An alternative would be a separate docker image, but I feel this would make it harder for users to find and opt in to using pre-releases.

**Additional context**
I am envisioning pre-releases to be more popular with users running local and less popular with users running GHA (it should require manual intervention in the end user's repo to upgrade to each pre-release, we would not want dependabot upgrading users to pre-releases).

**Comment by zkoppert** [comment]
Interesting idea. Not sure how many would actually use this. Wouldn't pre releasing be similar to pointing to master (`uses: github/super-linter@master`). I guess that a difference may be that pre-releases would be much faster since they don't build every time.

@admiralAwkbar @GaboFDC @Hanse00 would any of you use pre-releases if they were available?

**Comment by Hanse00** [comment]
Let's take a step back: What would a pre-release feature solve?

It sounds to me like the problem here is: We're unsure if the next version coming out, will be compatible with our codebase.
Is that accurate?

If that's the case, I don't think complicating the release process is the right solution. Instead we have:

1. Semantic versioning which (should) guarantee that any minor update will be compatible.
2. Releases. It may sound stupidly obvious, but I think normal releases already serve the purpose that is being suggested for pre-releases here. Instead of pinning your codebase to `latest`, test a specific version, make sure it works, and use that version. In the future when a new version comes out, you can test that, and update your CI script to use the new version.

If I'm totally misunderstanding the problem statement, then please forgive and enlighten me. But as it stands, my 2 cents would be: Don't complicate the release and versioning process unnecessarily.

**Comment by nemchik** [comment]
@Hanse00 Valid points, and I cannot disagree. My main focus on the idea of pre-releases was for when a new language is added, but I believe you are correct in that semantic versioning should solve that use case assuming users are making use of it and not pinning `latest` (which is kind of on them to learn from that mistake).

I had not considered semantic versioning as a solution to that problem.

**Comment by admiralAwkbar** [comment]
I personally use latest like a pre-release... It helps me find the things that we shipped that needs to be fixed before we cut another major release

**Comment by zkoppert** [comment]
@nemchik Ok to close? 

Also I have to say, I really appreciate your involvement in this project! Keep the ideas coming! 🎉
