### ISSUE TITLE
Where is my error

### ISSUE THREAD

**Issue by StephanKrauss** [github/super-linter#362]
Hello,

i have start super-linter local as a docker container.
I will test a single php file with the command:
docker run -e RUN_LOCAL=true -e VALIDATE_PHP=true -v c:/xampp1/htdocs/src/App/Action/FileDownload.php:/tmp/lint/FileDownload.php github/super-linter

I my test file there is a bug. Missing brace.
I can't see a error message.
What is wrong ?

Can i use a relativ path in the super-linter command. For example: ./src

Your sincerly 

Stephan

**Comment by admiralAwkbar** [comment]
Hey @StephanKrauss 
I think your issue is your pointing to the file and not the directory

the command should look more like:
`docker run -e RUN_LOCAL=true -e VALIDATE_PHP=true -v c:/xampp1/htdocs/src/App/Action:/tmp/lint github/super-linter:latest`

I tested and received the same behavior when pointing all the way to a file, and not the directory

**Comment by leviem1** [comment]
@admiralAwkbar Should I dedicate any time to tooling a check for this? I think it would be more intuitive to include an error message, but I don't imagine this is a top priority. Always happy to help!

**Comment by admiralAwkbar** [comment]
That would be super helpful to give users feedback that the passing was pointing to a file and not a directory... Could be a fairly easy fix
