### ISSUE TITLE
Strategy for multiple linters

### ISSUE THREAD

**Issue by GaboFDC** [github/super-linter#472]
Right now, we manage 2 linters for javascript (eslint and standard) and python (pylint and flake8). There may be later other languages that need support for multiple linters. 

The current strategy, in a general way, treats the 2 linters as if they were 2 languages. This cause the issue referred below:

> I mean, it would work as it does now, it's just not very convenient because pylint and flake are more or less treated like language switches. Perhaps there could be another configuration option where you can set the preferred linter(s) for JS, python, etc, without triggering that behavior, but that would go beyond the scope of this issue.

_Originally posted by @rolandgeider in https://github.com/github/super-linter/pull/455#issuecomment-663191074_

So the general idea proposed is to have a switch for the language, and an independent switch for the linter

**Comment by rolandgeider** [comment]
Specifically, the behaviour I mentioned in the issue linked above is that currently if a user wants to validate all languages but wants to use flake8 by setting VALIDATE_PYTHON_FLAKE8, it would mean that all other languages will have to be manually switched on as well

**Comment by admiralAwkbar** [comment]
@GaboFDC I think this leads us back to the original way they were disabled.
All were enabled by default, and if you stated `VALIDATE_LANGUAGE=false` it would then omit that language.

The logic feels like it should be:
- No validate flags = all run if found
- validate flag set to true = only validate that language
- validate flag set to false - omit only that language

thoughts?

**Comment by GaboFDC** [comment]
I think that would work fine, reading from #98 I think the problem was that you had to disable manually all linters you were not using, with this logic, you can either explicit define what you lint, lint all or lint all but something specific. 
Also maybe let's hear if @Hanse00 has some comments?

**Comment by artob** [comment]
Would it perhaps make sense to support `VALIDATE_PYTHON=flake8` (instead of `VALIDATE_PYTHON_FLAKE8=true`) and default to Pylint (for compatibility with existing users and previous configuration) if the value is set to `true`?

So as to avoid a combinatorial explosion of distinct environment variables as language and feature support expands over time.

**Comment by filips123** [comment]
> Would it perhaps make sense to support `VALIDATE_PYTHON=flake8` (instead of `VALIDATE_PYTHON_FLAKE8=true`) and default to Pylint (for compatibility with existing users and previous configuration) if the value is set to `true`?

Would this support if you want more linters for the same language, so for example, `VALIDATE_PYTHON=pylibnt,flake8`. Although with current Python linter that wouldn't be needed much because both linters target mainly the same thing when linting code, it would be useful if other linters (also in other languages), where, for example, one linter mainly focuses on code style, other focuses on syntax and another focuses on enforcing type declarations.
