### ISSUE TITLE
Where can I put ".flake8"?

### ISSUE THREAD

**Issue by ymd-h** [github/super-linter#541]
According to README, flake8 configuration file can be set by the environment value `PYTHON_FLAKE8_CONFIG_FILE`.

However, explicitly setting filename and putting that config file (e.g. .flake8) at repository root doesn't work (flake8 still use default settings).

Where can I put the config file?

---

It seems that even user set config file name, the config file name is concatenated with `DEFAULT_RULES_LOCATION`. (This is  true for not only flake8, but also other linters, too.)
https://github.com/github/super-linter/blob/c4708f880319b174ccb95bce414e4dc5c0a49004/lib/linter.sh#L108-L109

https://github.com/github/super-linter/blob/c4708f880319b174ccb95bce414e4dc5c0a49004/lib/linter.sh#L25

**Comment by bazzadp** [comment]
According to the README the config file *name* can be set with this - so presume that means you can't fully specify it with a path as well.

[All override files need to be in `.github/linters` folder](https://github.com/github/super-linter#template-rules-files) otherwise the defaults will be used. You can specify a `LINTER_RULES_PATH` config file - but then it will override all linters and not just flake8.

Alternatively, [apparently a symlink might work](https://github.com/github/super-linter/issues/174#issuecomment-646680435) if you want to avoid duplicating a config file.

**Comment by admiralAwkbar** [comment]
@ymd-h as long as the file is in the `.github/linters/` folder it will be parsed.

**Comment by ymd-h** [comment]
@bazzadp and @admiralAwkbar 
Thank you for your kind support!

It worked for me.(Putting at `.github/linters/.flake8`)

**Comment by avadhanij6si** [comment]
Commenting on this in search of clarity. Is there a specific reason for this design decision? `.flake8` and `.pyproject.toml` files don't reside in such locations usually.

They sit closer to the code. This is particularly true for mono-repos where there are many services co-existing.
