### ISSUE TITLE
Default to main and then master

### ISSUE THREAD

**Issue by IlanCosman** [github/super-linter#698]
**Is your feature request related to a problem? Please describe.**

Following the guidance of github, many developers are moving to `main` as their default branch. Saving developers from the very small hindrance of using `DEFAULT_BRANCH: main` would contribute to smoothing the transition.

**Describe the solution you'd like**

The default branch should be `main`. If it does not exist, use `master`, given that many repositories will continue using this name.

**Comment by admiralAwkbar** [comment]
@IlanCosman Very valid and great points. Due to legacy issues, we need to find a good way to check the repository and look for source branches. I need to take a look and see the insides and how this could be easily achieved. If you have some cycles, maybe you can take a look and see if it could be an easy fix as well :)

Thanks

**Comment by IlanCosman** [comment]
It _seems_ like it should be fairly easy, but I'm sure I'm missing something. 

I forked the repo and changed `DEFAULT_BRANCH="${DEFAULT_BRANCH:-master}"` to `DEFAULT_BRANCH="${DEFAULT_BRANCH:-origin/HEAD}"`. The dev action passed successfully.

I'm not sure how to test my changes elsewhere. I suppose I'd have to set up a dockerhub account, publich my image, and then try using it in another repository with various silly default branches?

**Comment by IlanCosman** [comment]
Oh, no it seems to work with `uses: IlanCosman/super-linter@v3`, cool.

**Comment by IlanCosman** [comment]
After a bit of testing I realize that I don't understand what the `DEFAULT_BRANCH` variable is supposed to do in the slightest. I'll leave this issue open since it seems to mean something to you.

**Comment by HorizonNet** [comment]
Instead of defining the default branch it would be better (and more flexible) to grab the default branch of the repository. With that the user does not need to care about setting the configuration. The configuration can then be used if the user wants to use another branch as the default branch used by super-linter.

**Comment by admiralAwkbar** [comment]
@HorizonNet The root of the issue:
We are trying to find the files that have changed between the current SHA and the branch it was built off of.
This data is hard to come by due to how people trigger the build pipeline.
- They could be running through GitHub actions
- They could be running locally
- They could be running from other git tools

This makes it hard for us to be able to parse from some commonly known locations.
The simple answer is to set the default if not `master` again, some time in the future, we will need to default to `main`

**Comment by HorizonNet** [comment]
Ok, got your point. Was only thinking in terms of a GitHub action.
