### ISSUE TITLE
Support the customization of linter invocations

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#987]
**Is your feature request related to a problem? Please describe.**

super-linter doesn't currently support any customization of the commands and the options it uses. Apparently, this is a feature that users want: #891, #986, #692, #680. #507, #498 

We can use this issue to design an implementation.

**Describe the solution you'd like**

1. Users should be able to personalize commands and options.
1. Dynamically initialize variables as much as possible.
1. Rely on defaults if the user don't specify additional customizations.

**Describe alternatives you've considered**

For some linters, there's a wide consensus on which options are "right" for the vast majority of use cases. The issues above clearly demonstrate that for many linters this is not true. Additionally, not all linters support configuration files, or not every option is configurable via configuration files (for some reason).

cc @admiralAwkbar @GaboFDC

**Comment by GaboFDC** [comment]
From the top of my mind, we could create new ENV vars, like <LINTER>_CLI_ARGS. leaving the current ones as default, and use that variable on the linter invocation. Seems plausible. wdyt?

**Comment by ferrarimarco** [comment]
The `_CLI_ARGS` approach works if we don't want to also let users customize the name of command to run, besides the arguments, which makes sense, because the command name depends on how we build the container image.

**Comment by nvuillam** [comment]
Something like that maybe ?

https://nvuillam.github.io/mega-linter/descriptors/javascript_eslint/#mega-linter-configuration

I remained compliant with super-linter config, a merge could still be done if you wished so :)

**Comment by james-stocks** [comment]
I think this is making the dotnet linter very limited because dotnet-format [doesn't do naming or language linting without the `--fix-style` option](https://github.com/dotnet/format/blob/master/docs/Supported-.editorconfig-options.md#core-options)

**Comment by bwmills** [comment]
@ferrarimarco - hello, hope all is well.

We're using Actions and followed a quick start from [the docs](https://docs.github.com/en/actions/quickstart) and ran the `Super-Linter` workflow against a DevOps infrastructure repo with Kubernetes configs, ops scripts, etc. The Kubernetes configs include CRDs, and so just as in #891 the job fails due to Kubeval validation failure:

```
2021-02-01 02:13:53 [ERROR]   Found errors in [kubeval] linter!
2021-02-01 02:13:53 [ERROR]   Error code: 1. Command output:
------
ERR  - /github/workspace/ops/eks/eks.yml: Failed initializing schema https://kubernetesjsonschema.dev/master-standalone-strict/clusterconfig-eksctl-v1alpha5.json: Could not read schema from HTTP, response status is 404 Not Found
------
```

I've tried to trace this through various threads and landed here - hopefully I'm in the right place. It looks like [kubeval](https://kubeval.instrumenta.dev/#crds) supports the `--ignore-missing-schemas` flag for CRDs, but that here in the `super-linter`, the goal is to make this option configurable ... and that change is open in this issue.

I did get a bit confused when I saw [this](https://github.com/github/super-linter/actions/runs/320797034/workflow) - I wasn't sure whether that was implying the change is complete?

If you can provide an update on this that would be much appreciated. Ultimately we're looking for a way to use the `super-linter` and also specify `--ignore-missing-schemas` for Kubeval as part of the YAML config for Actions.

**Comment by ferrarimarco** [comment]
Hi @bwmills ! Long story short: that PR fixed the issue for Kubeval, but it was introducing an arbitrary change. What about the users who needed that check?

In the end, we decided to close it, and provide a more flexible mechanism to customize the linter command invocation. This is useful for linters that don't offer a configuration file, or don't expose all their configurations knobs via a configuration file.

Feel free to open a PR in this direction if you have spare cycles :)

**Comment by bwmills** [comment]
@ferrarimarco many thanks for this update!

Apologies that I am still slow on getting the full picture. I think the PR you're referring to is [#892](https://github.com/github/super-linter/pull/892) is that right? If so, then I understand what you're saying.

Fwiw, from an Actions / super-linter config standpoint, I was envisioning the `--ignore-missing-schemas` flag as optional to the user, so as you said, users who need that check can opt to not set that flag.

**Comment by cilindrox** [comment]
Can this be reopened? not being able to configure `kubeval` means its of no use to any projects with CRDs unless there's a way of passing the `--ignore-missing-schemas` flag.

**Comment by B-Souty** [comment]
This issue really need to be addressed. I'm having an issue with the terraform linter tflint because super-linter doesn't support custom flags.

tflint doesn't lint recursively by default and due to the structure of our repository, super-linter in its current state doesn't lint any of our terraform file.
